name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ "main", "priyanshi" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: 'Use gcloud CLI'
      run: gcloud info


    - name: 'Write GCP service account key to file'
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-sa-key.json

    - name: 'Set read permissions for the service account key file'
      run: chmod 600 $HOME/gcloud-sa-key.json

    - name: 'Activate Service Account'
      run: gcloud auth activate-service-account --key-file=$HOME/gcloud-sa-key.json
    
    - name: Deploy to Cloud Functions
      run: |-
        gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }} \
          --region=${{ secrets.GCP_REGION }} \
          --entry-point=main \
          --gen2 \
          --runtime=python310 \
          --trigger-http \
          --allow-unauthenticated \
          --source=. \
          --memory=2000MB
