name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ "main", "priyanshi" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to Google Cloud Functions
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'


    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     source venv/bin/activate
    #     pytest
    #   shell: bash


    # - name: Lint code
    #   run: |
    #     source venv/bin/activate
    #     flake8 .

    # - name: Security scan
    #   run: |
    #     source venv/bin/activate
    #     bandit -r .

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'https://iam.googleapis.com/projects/222808868980/locations/global/workloadIdentityPools/githubactions/providers/github'
        service_account: '222808868980-compute@developer.gserviceaccount.com'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Activate Service Account
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Cloud Functions
      run: |-
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --region=${{ env.REGION }} \
          --entry-point=main \
          --gen2 \
          --runtime=python310 \
          --trigger-http \
          --allow-unauthenticated \
          --source=. \
          --memory=2000MB

      env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
          FUNCTION_NAME: ${{ secrets.GCP_FUNCTION_NAME }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # - name: Notify
    #   if: success()
    #   uses: slackapi/slack-github-action@v1.19.0
    #   with:
    #     slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
    #     channels: '#deployments'
    #     text: 'Deployment to Google Cloud Functions was successful.'

    # - name: Notify
    #   if: failure()
    #   uses: slackapi/slack-github-action@v1.19.0
    #   with:
    #     slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
    #     channels: '#deployments'
    #     text: 'Deployment to Google Cloud Functions failed.'